samples: sample.tsv
Patient: Patient.tsv

ref:
  bwa:
    # reference genome
    species: home_sapiens
    release: 98
    build: GRCH38
  gatk:
    BQSR:
      dbsnp: "ref_data/*"
      dbsnp1000G: "ref_data/*"
      dbindle100G: "ref_data/*"

    mutation_calling: 
      PoN:
      germline:
      

params:
  java: "-Xmx12G -Djava.io.tmpdir=~/tmp"
  gatk:
    gatk_baserecalibrator: ""
    mutect2: ""
  hla_typing:
  neoantigens_prediction:
  
